// Auto-generated by: supabase gen types typescript --project-id <YOUR_PROJECT_ID> > src/types/supabase.ts
// This file will be replaced once the Supabase project is created.
export type Database = Record<string, unknown>
